# Generated by Django 5.0.7 on 2024-09-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=100)),
                ('turf_address', models.TextField()),
                ('turf_city', models.CharField(max_length=50)),
                ('turf_state', models.CharField(max_length=50)),
                ('turf_zip_code', models.CharField(max_length=10)),
                ('turf_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('turf_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('turf_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=10)),
                ('surface_type', models.CharField(choices=[('artificial', 'Artificial Grass'), ('natural', 'Natural Grass'), ('concrete', 'Concrete')], max_length=20)),
                ('size', models.CharField(help_text='E.g., 5-a-side, 7-a-side, 11-a-side', max_length=20)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum players allowed')),
                ('status', models.IntegerField(choices=[(1, 'Verified'), (2, 'Blocked'), (3, 'Pending')], default=3)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('closed_days', models.CharField(help_text='Days turf is closed, e.g., Sunday', max_length=50)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peak_hour_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('turf_contact_phone', models.CharField(max_length=10)),
                ('turf_contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
