# Generated by Django 5.0.7 on 2024-09-24 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_turfdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='turf_images/')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.turfdetails')),
            ],
        ),
    ]
