# Generated by Django 5.0.7 on 2024-09-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_turfimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TurfImage',
        ),
    ]
