# Generated by Django 5.0.7 on 2024-09-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_turfdetails_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turfdetails',
            name='image',
        ),
        migrations.AddField(
            model_name='turfdetails',
            name='image1',
            field=models.ImageField(default='turf_images/download_1.jpeg', upload_to='turf_images/'),
        ),
        migrations.AddField(
            model_name='turfdetails',
            name='image2',
            field=models.ImageField(default='turf_images/download_1.jpeg', upload_to='turf_images/'),
        ),
        migrations.AddField(
            model_name='turfdetails',
            name='image3',
            field=models.ImageField(default='turf_images/download_1.jpeg', upload_to='turf_images/'),
        ),
        migrations.AddField(
            model_name='turfdetails',
            name='image4',
            field=models.ImageField(default='turf_images/download_1.jpeg', upload_to='turf_images/'),
        ),
        migrations.AddField(
            model_name='turfdetails',
            name='image5',
            field=models.ImageField(default='turf_images/download_1.jpeg', upload_to='turf_images/'),
        ),
    ]
