# Generated by Django 5.0.7 on 2024-09-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_turfdetails_image_turfdetails_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfdetails',
            name='image1',
            field=models.ImageField(blank=True, default='turf_images/download_1.jpeg', null=True, upload_to='turf_images/'),
        ),
        migrations.AlterField(
            model_name='turfdetails',
            name='image2',
            field=models.ImageField(blank=True, default='turf_images/download_1.jpeg', null=True, upload_to='turf_images/'),
        ),
        migrations.AlterField(
            model_name='turfdetails',
            name='image3',
            field=models.ImageField(blank=True, default='turf_images/download_1.jpeg', null=True, upload_to='turf_images/'),
        ),
        migrations.AlterField(
            model_name='turfdetails',
            name='image4',
            field=models.ImageField(blank=True, default='turf_images/download_1.jpeg', null=True, upload_to='turf_images/'),
        ),
        migrations.AlterField(
            model_name='turfdetails',
            name='image5',
            field=models.ImageField(blank=True, default='turf_images/download_1.jpeg', null=True, upload_to='turf_images/'),
        ),
    ]
