# Generated by Django 5.0.7 on 2024-10-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_turfdetails_image1_remove_turfdetails_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfBookingDeatils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(editable=False, max_length=200, unique=True)),
                ('turf_name', models.CharField(max_length=100)),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('date', models.DateField()),
                ('total_ammount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
