# Generated by Django 5.0.7 on 2025-04-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_turfbookingdeatils'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TurfBookingDeatils',
            new_name='TurfBookingDetails',
        ),
        migrations.RemoveField(
            model_name='turfdetails',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='turfdetails',
            name='opening_time',
        ),
    ]
