# Generated by Django 5.0.7 on 2025-04-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_turfbookingdeatils_turfbookingdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfdetails',
            name='slotes',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
