# Generated by Django 5.0.7 on 2025-04-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_turfdetails_slotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfdetails',
            name='slotes',
            field=models.JSONField(default=list, null=True),
        ),
    ]
