# Generated by Django 5.0.7 on 2025-04-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_turfdetails_slotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfdetails',
            name='turf_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
